- hosts: localhost
  connection: local
  vars:
    nautobot_db_name: nautobot
    nautobot_db_username: nautobot 
    nautobot_db_password: E1x3oasg 
    cert_path: /etc/ssl
    country: US
    state: TX
    city: Austin
    domain: nautobot.example.com
    allowed_hosts:
    - "*"

  tasks:
  - name: CREATE NAUTOBOT GROUP
    ansible.builtin.group:
      name: nautobot
      system: yes
      state: present

  - name: CREATE NAUTOBOT USER
    ansible.builtin.user:
      name: nautobot
      system: yes
      shell: /bin/bash
      home: /opt/nautobot
      group: nautobot
      state: present

  - name: INSTALL PACKAGES 
    ansible.builtin.apt:
      name:
      - postgresql
      - libpq-dev
      - redis-server
      update_cache: yes
      state: present

  - name: UPDATE PG_HBA.CONF
    ansible.builtin.template:
      src: pg_hba.conf
      dest: /etc/postgresql/12/main/pg_hba.conf
      owner: postgres
      group: postgres
      mode: "0600"
    register: hba_update

  - name: RESTART POSTGRESQL
    ansible.builtin.service:
      name: postgresql
      state: restarted
    when: hba_update.changed

  - name: CREATE NAUTOBOT DATABASE
    community.postgresql.postgresql_db:
      name: nautobot
      state: present

  - name: CREATE NAUTOBOT DATABASE USER ACCOUNT AND GRANT PRIVILEGES TO DATABASE
    community.postgresql.postgresql_user:
      db: "{{ nautobot_db_name }}"
      name: "{{ nautobot_db_username }}"
      password: "{{ nautobot_db_password }}"
      priv: ALL
      state: present

  - name: SET NAUTOBOT HOME DIRECTORY PERMISSIONS
    ansible.builtin.file:
      name: /opt/nautobot
      owner: nautobot
      group: nautobot
      mode: 0775
      state: directory

  - name: UPGRADE PIP
    ansible.builtin.pip:
      name: pip
      state: latest
      virtualenv: /opt/nautobot/venv
      virtualenv_command: python3 -m venv

  - name: INSTALL NAUTOBOT FROM PIP
    ansible.builtin.pip:
      name: nautobot
      state: latest
      virtualenv: /opt/nautobot/venv
      virtualenv_command: python3 -m venv

  - name: SET NAUTOBOT HOME DIRECTORY PERMISSIONS
    ansible.builtin.file:
      name: /opt/nautobot
      owner: nautobot
      group: nautobot
      recurse: yes
      state: directory

  - name: CREATE NAUTOBOT CONFIG DIRECTORY 
    ansible.builtin.file:
      name: /opt/nautobot/.nautobot
      owner: nautobot
      group: nautobot
      mode: "0755"
      state: directory

  - name: RUN MAKEMIGRATIONS
    ansible.builtin.command: ./venv/bin/nautobot-server init 
    become_user: nautobot

  - name: UPDATE NAUTOBOT CONFIG
    ansible.builtin.template:
      src: nautobot_config.py
      dest: /opt/nautobot/.nautobot/nautobot_config.py
      owner: nautobot
      group: nautobot
      mode: 0644

  - name: RUN MAKEMIGRATIONS
    ansible.builtin.command: ./venv/bin/nautobot-server makemigrations --config=/opt/nautobot/.nautobot/nautobot_config.py
    become_user: nautobot

  - name: RUN MIGRATE
    ansible.builtin.command: ./venv/bin/nautobot-server migrate --config=/opt/nautobot/.nautobot/nautobot_config.py
    become_user: nautobot
